version: '3'

services:
  mongodb_app:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
  nodejs_app:
    build: .
    image: nodejs:18.13.0
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - mongodb_app
    environment:
      MONGO_URL: mongodb://user:password@mongodb_app/admin
      PORT: 8000